joint_limits:
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853