manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
#  kinematics_solver: ur5_demo_manipulator_kinematics/IKFastKinematicsPlugin
  kinematics_solver_attempts: 10
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.05
